/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Java.ListRandom;
import Java.koneksi;
import Java.modelTabelKelompok;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author Dii
 */
public class Master_Kelompok extends javax.swing.JFrame {

    private Java.koneksi koneksi;
    private Connection con;
    private ResultSet hasil;
    private Statement stat;
    private Java.ListKelompok listKelompok;
    private List<Java.ListKelompok> list; 
    private TableModel model;
    private String query;
    private int id;
    private String kode_kelompok;
    private String nama_kelompok;
    private String bool , baru;
    
    public Master_Kelompok() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilTabel();
        fCari.requestFocusInWindow();
        dTambahUpdateKelompok.setLocationRelativeTo(null);
        fKode.requestFocusInWindow();
        bool = "false";
    }
    
    public String tampilTabel(){
        String data = "";
        koneksi = new koneksi();
        con = (Connection) koneksi.Connect();
        try{
          data ="select *  from kelompok";
          hasil = koneksi.ambilData(data);
          System.out.println("sukses query tampil tabel");
          setModel(hasil);
        }catch(Exception e){
            System.out.println("Error tampil tabel");
        }
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dTambahUpdateKelompok = new javax.swing.JDialog();
        fKode = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        fBatal = new javax.swing.JButton();
        fSimpan = new javax.swing.JButton();
        jKelompok = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        fTanggal = new javax.swing.JLabel();
        fTambah = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        fTabel = new javax.swing.JTable();
        fCari = new javax.swing.JTextField();
        fEdit = new javax.swing.JButton();

        dTambahUpdateKelompok.setTitle("Tambah/Update Kelompok");
        dTambahUpdateKelompok.setBackground(new java.awt.Color(255, 255, 255));
        dTambahUpdateKelompok.setResizable(false);
        dTambahUpdateKelompok.setSize(new java.awt.Dimension(375, 138));
        dTambahUpdateKelompok.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dTambahUpdateKelompokWindowOpened(evt);
            }
        });
        dTambahUpdateKelompok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dTambahUpdateKelompokKeyPressed(evt);
            }
        });

        fKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKodeActionPerformed(evt);
            }
        });
        fKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKodeKeyPressed(evt);
            }
        });

        jLabel30.setText("Kode Kelompok");

        jLabel31.setText("Nama Kelompok");

        fNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaActionPerformed(evt);
            }
        });
        fNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNamaKeyPressed(evt);
            }
        });

        fBatal.setText("Batal");
        fBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBatalActionPerformed(evt);
            }
        });
        fBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fBatalKeyPressed(evt);
            }
        });

        fSimpan.setText("Simpan");
        fSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSimpanActionPerformed(evt);
            }
        });
        fSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fSimpanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dTambahUpdateKelompokLayout = new javax.swing.GroupLayout(dTambahUpdateKelompok.getContentPane());
        dTambahUpdateKelompok.getContentPane().setLayout(dTambahUpdateKelompokLayout);
        dTambahUpdateKelompokLayout.setHorizontalGroup(
            dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dTambahUpdateKelompokLayout.createSequentialGroup()
                .addGroup(dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dTambahUpdateKelompokLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(67, 67, 67)
                        .addGroup(dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fNama, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(fKode)))
                    .addGroup(dTambahUpdateKelompokLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(fSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fBatal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dTambahUpdateKelompokLayout.setVerticalGroup(
            dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dTambahUpdateKelompokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fKode)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(dTambahUpdateKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fBatal)
                    .addComponent(fSimpan))
                .addContainerGap())
        );

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jKelompok.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setText("Kelompok Form");

        fTanggal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fTanggal.setText("Tanggal | Waktu");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(fTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(fTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fTambah.setText("Tambah Kelompok");
        fTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTambahActionPerformed(evt);
            }
        });
        fTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fTambahKeyPressed(evt);
            }
        });

        fTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama"
            }
        ));
        fTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fTabelMouseClicked(evt);
            }
        });
        fTabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fTabelKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(fTabel);

        fCari.setToolTipText("Search");
        fCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fCariFocusLost(evt);
            }
        });
        fCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fCariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fCariKeyReleased(evt);
            }
        });

        fEdit.setText("Edit");
        fEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fEditActionPerformed(evt);
            }
        });
        fEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fEditKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jKelompokLayout = new javax.swing.GroupLayout(jKelompok);
        jKelompok.setLayout(jKelompokLayout);
        jKelompokLayout.setHorizontalGroup(
            jKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jKelompokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jKelompokLayout.createSequentialGroup()
                        .addComponent(fTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fCari, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jKelompokLayout.setVerticalGroup(
            jKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jKelompokLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTambah)
                    .addComponent(fCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fEdit))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTambahActionPerformed
        dTambahUpdateKelompok.show();
        dTambahUpdateKelompok.setLocationRelativeTo(null);
        fKode.setText("");
        fNama.setText("");
        baru = "NEW";
    }//GEN-LAST:event_fTambahActionPerformed

    private void fCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fCariFocusGained
        //placeHolderGain(vSearchKelompok, null);
    }//GEN-LAST:event_fCariFocusGained

    private void fCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fCariFocusLost
        //placeHolderGain(vSearchKelompok, null);
    }//GEN-LAST:event_fCariFocusLost

    private void fBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBatalActionPerformed
       dTambahUpdateKelompok.dispose();
       bersih();
    }//GEN-LAST:event_fBatalActionPerformed

    private void fEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fEditActionPerformed
        if("true".equals(bool)){
           dTambahUpdateKelompok.show();
            dTambahUpdateKelompok.setLocationRelativeTo(null);
            ambilDataTabel();
            fKode.setText(kode_kelompok);
            fNama.setText(nama_kelompok);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih salah satu data di tabel terlebih dahulu");
        }
        
        
        
    }//GEN-LAST:event_fEditActionPerformed

    private void fCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fCariKeyReleased
        try{
        query= "SELECT * FROM kelompok where kode_kelompok like '%"+fCari.getText()+"%' or nama_kelompok like '%"+fCari.getText()+"%'";
        hasil = koneksi.ambilData(query);
        setModel(hasil);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
            fTabel.requestFocusInWindow();
        }
        }catch (Exception e) {
        }
    }//GEN-LAST:event_fCariKeyReleased

    private void fSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSimpanActionPerformed
        if("".equals(fKode.getText()) && "".equals(fNama.getText())){
            JOptionPane.showMessageDialog(null, "Gagal, Lengkapi semua data input!");     
        }else{
            simpanAtauEdit();
        }
        
    }//GEN-LAST:event_fSimpanActionPerformed

    private void fTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fTabelMouseClicked
        if (evt.getClickCount() == 1){
            bool ="true";
        }
        if (evt.getClickCount() == 2){
           dTambahUpdateKelompok.show();
            dTambahUpdateKelompok.setLocationRelativeTo(null);
            ambilDataTabel();
            fKode.setText(kode_kelompok);
            fNama.setText(nama_kelompok);
        }
    }//GEN-LAST:event_fTabelMouseClicked

    private void fKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKodeActionPerformed
       fNama.requestFocusInWindow();
    }//GEN-LAST:event_fKodeActionPerformed

    private void fNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaActionPerformed
        fSimpan.requestFocusInWindow();
    }//GEN-LAST:event_fNamaActionPerformed

    private void fSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSimpanKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           simpanAtauEdit();
       }
       if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
    }//GEN-LAST:event_fSimpanKeyPressed

    private void fTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTambahKeyPressed
     if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
    }//GEN-LAST:event_fTambahKeyPressed

    private void fEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fEditKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }  
    }//GEN-LAST:event_fEditKeyPressed

    private void fTabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTabelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {  
            bool="true";
           if("true".equals(bool)){
                dTambahUpdateKelompok.show();
                dTambahUpdateKelompok.setLocationRelativeTo(null);
                ambilDataTabel();
                fKode.setText(kode_kelompok);
                fNama.setText(nama_kelompok);
            }else{
                JOptionPane.showMessageDialog(null, "Pilih salah satu data di tabel terlebih dahulu");
        }
          
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
        if (evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP) {
            bool="true";
        }
    }//GEN-LAST:event_fTabelKeyPressed

    private void fCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fCariKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
    }//GEN-LAST:event_fCariKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
    }//GEN-LAST:event_formKeyPressed

    private void dTambahUpdateKelompokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTambahUpdateKelompokKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            dTambahUpdateKelompok.setVisible(false);
        }
    }//GEN-LAST:event_dTambahUpdateKelompokKeyPressed

    private void fKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKodeKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            dTambahUpdateKelompok.setVisible(false);
            id=0;
        }
    }//GEN-LAST:event_fKodeKeyPressed

    private void fNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNamaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            dTambahUpdateKelompok.setVisible(false);
            id=0;
        }
    }//GEN-LAST:event_fNamaKeyPressed

    private void fBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fBatalKeyPressed
       this.dispose();
       bersih();
       if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            dTambahUpdateKelompok.setVisible(false);
            id=0;
        }
    }//GEN-LAST:event_fBatalKeyPressed

    private void dTambahUpdateKelompokWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dTambahUpdateKelompokWindowOpened
        fKode.requestFocusInWindow();
    }//GEN-LAST:event_dTambahUpdateKelompokWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_Kelompok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_Kelompok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_Kelompok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_Kelompok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_Kelompok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dTambahUpdateKelompok;
    private javax.swing.JButton fBatal;
    private javax.swing.JTextField fCari;
    private javax.swing.JButton fEdit;
    private javax.swing.JTextField fKode;
    private javax.swing.JTextField fNama;
    private javax.swing.JButton fSimpan;
    private javax.swing.JTable fTabel;
    private javax.swing.JButton fTambah;
    private javax.swing.JLabel fTanggal;
    private javax.swing.JPanel jKelompok;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
    private void setModel(ResultSet hasil){
        try {
            list = new ArrayList<Java.ListKelompok>();
            while(hasil.next()){
                listKelompok = new Java.ListKelompok();
                listKelompok.setId_kelompok(hasil.getInt("id_kelompok"));
                listKelompok.setKode_kelompok(hasil.getString("kode_kelompok"));
                listKelompok.setNama_kelompok(hasil.getString("nama_kelompok"));
                list.add(listKelompok);
            }
            model = new modelTabelKelompok(list);
            fTabel.setModel(model);
            fTabel.getColumnModel().getColumn(0).setPreferredWidth(30);
            fTabel.getColumnModel().getColumn(1).setPreferredWidth(240);
            fTabel.getColumnModel().getColumn(2).setPreferredWidth(240);
            fTabel.getColumnModel().getColumn(0).setMinWidth(30);
            fTabel.getColumnModel().getColumn(1).setMinWidth(240);
            fTabel.getColumnModel().getColumn(2).setMinWidth(240);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void simpanAtauEdit(){
        
        if(id > 0 && baru != "NEW"){
            edit();
        }else{
            String kode = this.fKode.getText();
            String nama = this.fNama.getText();
            int angka = 0;

            try{
                query= "SELECT id_kelompok FROM kelompok ORDER BY id_kelompok DESC LIMIT 1";
                hasil = koneksi.ambilData(query);
                while(hasil.next()){
                    angka = hasil.getInt("id_kelompok");
                    System.out.println(angka);

                    id = angka + 1;
                    System.out.println("id"+id);


                    String sql= "Insert into kelompok values ('"+id+"', '"+kode+"', '"+nama+"')";
                    System.out.println(sql);
                    koneksi.simpanData(sql);

                    JOptionPane.showMessageDialog(null,"Data sukses di input");
                    dTambahUpdateKelompok.dispose();

                    tampilTabel();
                    bersih();
                }

            }catch (SQLException e){
                System.out.println();
            }
        }    
    }
    
    private void edit(){
        try {
           String sql= "Update kelompok set kode_kelompok=?, nama_kelompok=? where id_kelompok=?" ;
            PreparedStatement p = (PreparedStatement) koneksi.Connect().prepareStatement(sql);
                p.setString(1, fKode.getText().toString());
                p.setString(2, fNama.getText().toString());
                p.setInt(3, id);
                p.executeUpdate();

                dTambahUpdateKelompok.dispose();
                tampilTabel();
                System.out.print(p);
                 JOptionPane.showMessageDialog(null,"Data sukses di edit");
                 bersih();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void ambilDataTabel(){
        int row= fTabel.getSelectedRow();
        id  = ((Integer)fTabel.getValueAt(row, 0));
        kode_kelompok = ((String)fTabel.getValueAt(row, 1));
        nama_kelompok = ((String)fTabel.getValueAt(row, 2));
    }
    
    private void bersih(){
        id = 0;
        fKode.setText("");
        fNama.setText("");
    }
}
