/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Java.ListRandom;
import Java.koneksi;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Master_Customer_NewEdit extends javax.swing.JFrame {

    private Java.koneksi koneksi;
    private Connection con;
    private ResultSet hasil;
    private Statement stat;
    private String kode_salesman, nama_salesman, alamat, telepon, 
            handphone, contact, kota, propinsi, keterangan, wilayah, top, hari, kodecustomer, nama_wilayah;
    private Integer id_top, hargaJual, LimitPiutang, sisa, id, id_wilayah, status;
    private Java.ListRandom list;
    private String dataTombol;
    
    public Master_Customer_NewEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
        WilayahCombo();
        fKode.requestFocus();
        ComboKodeSalesman();
        fKodeSalesman.removeItemAt(0);
        ComboNamaSalesman();
        list = new ListRandom();
        kodecustomer = list.getKode_customer();
        if(kodecustomer!="new"){
            tampilDataEdit();
        }else{
            fDeactive.setSelected(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        fKode = new javax.swing.JTextField();
        fSimpan = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        fBatal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fAlamat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fTelepon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fHandphone = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fContact = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fKota = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fPropinsi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        fKeterangan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        fHargaJual = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        fKodeSalesman = new javax.swing.JComboBox<>();
        fNamaSalesman = new javax.swing.JComboBox<>();
        fHari = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        fTOP = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        fLimit = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        fSisa = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        fWilayah = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        fDeactive = new javax.swing.JRadioButton();
        fActive = new javax.swing.JRadioButton();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Kode");

        fKode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fKode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fKodeMouseClicked(evt);
            }
        });
        fKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKodeKeyPressed(evt);
            }
        });

        fSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/if_stock_save_20659.png"))); // NOI18N
        fSimpan.setText("F12-Save");
        fSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSimpanMouseClicked(evt);
            }
        });
        fSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fSimpanKeyPressed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cancel (3).png"))); // NOI18N
        fBatal.setText("Esc - Exit");
        fBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fBatalMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nama");

        fNama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNamaMouseClicked(evt);
            }
        });
        fNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNamaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Alamat");

        fAlamat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fAlamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fAlamatMouseClicked(evt);
            }
        });
        fAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fAlamatKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Telepon");

        fTelepon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fTelepon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fTeleponMouseClicked(evt);
            }
        });
        fTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fTeleponKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Handphone");

        fHandphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fHandphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fHandphoneMouseClicked(evt);
            }
        });
        fHandphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fHandphoneKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Contact");

        fContact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fContactMouseClicked(evt);
            }
        });
        fContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fContactKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Kota");

        fKota.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fKota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fKotaMouseClicked(evt);
            }
        });
        fKota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKotaKeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Propinsi");

        fPropinsi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fPropinsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fPropinsiMouseClicked(evt);
            }
        });
        fPropinsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fPropinsiKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Keterangan");

        fKeterangan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fKeterangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fKeteranganMouseClicked(evt);
            }
        });
        fKeterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKeteranganKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Harga Jual");

        fHargaJual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HARGA JUAL 1", "HARGA JUAL 2", "HARGA JUAL 3" }));
        fHargaJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fHargaJualKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Salesman");

        fKodeSalesman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fKodeSalesmanMouseClicked(evt);
            }
        });
        fKodeSalesman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKodeSalesmanActionPerformed(evt);
            }
        });
        fKodeSalesman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKodeSalesmanKeyPressed(evt);
            }
        });

        fNamaSalesman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaSalesmanActionPerformed(evt);
            }
        });
        fNamaSalesman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNamaSalesmanKeyPressed(evt);
            }
        });

        fHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENIN", "SELASA", "RABU", "KAMIS", "JUMAT", "SABTU", "MINGGU" }));
        fHari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fHariKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("T.O.P");

        fTOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TUNAI", "30 HARI", "120 HARI", "45 HARI", "60 HARI", "75 HARI", "90 HARI", "14 HARI", "7 HARI" }));
        fTOP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fTOPKeyPressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Limit Piutang");

        fLimit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fLimit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fLimitMouseClicked(evt);
            }
        });
        fLimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fLimitKeyPressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Sisa");

        fSisa.setBackground(new java.awt.Color(204, 255, 204));
        fSisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fSisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSisaMouseClicked(evt);
            }
        });
        fSisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fSisaKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Wilayah");

        fWilayah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fWilayahKeyPressed(evt);
            }
        });

        fDeactive.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(fDeactive);
        fDeactive.setText("DEACTIVE");
        fDeactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fDeactiveActionPerformed(evt);
            }
        });
        fDeactive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fDeactiveKeyPressed(evt);
            }
        });

        fActive.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(fActive);
        fActive.setText("ACTIVE");
        fActive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fActiveKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fDeactive)
                        .addGap(0, 0, 0)
                        .addComponent(fActive))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fKode, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(fNama)
                        .addComponent(fAlamat)
                        .addComponent(fTelepon)
                        .addComponent(fHandphone)
                        .addComponent(fContact)
                        .addComponent(fKeterangan)
                        .addComponent(fHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fPropinsi, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(fKota))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fKodeSalesman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNamaSalesman, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fHari, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fTOP, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fSimpan)
                            .addComponent(fBatal))))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fKode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fHandphone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fContact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fKota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(fPropinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(fKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(fHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(fKodeSalesman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNamaSalesman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(fTOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(fSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(fWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDeactive)
                    .addComponent(fActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fKodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fKodeMouseClicked
        //       Penjualan_Penjualan_Pilihcustomer pppc = new Penjualan_Penjualan_Pilihcustomer();
        //       pppc.setVisible(true);
        //       pppc.setFocusable(true);
    }//GEN-LAST:event_fKodeMouseClicked

    private void fNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNamaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fNamaMouseClicked

    private void fAlamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fAlamatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fAlamatMouseClicked

    private void fTeleponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fTeleponMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fTeleponMouseClicked

    private void fHandphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fHandphoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fHandphoneMouseClicked

    private void fContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fContactMouseClicked

    private void fKotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fKotaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fKotaMouseClicked

    private void fPropinsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fPropinsiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fPropinsiMouseClicked

    private void fKeteranganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fKeteranganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fKeteranganMouseClicked

    private void fLimitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fLimitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fLimitMouseClicked

    private void fSisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSisaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fSisaMouseClicked

    private void fKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKodeKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fNama.requestFocusInWindow();
       }
       if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fKodeKeyPressed

    private void fNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fAlamat.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fNamaKeyPressed

    private void fAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAlamatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fTelepon.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
        
    }//GEN-LAST:event_fAlamatKeyPressed

    private void fTeleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTeleponKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fHandphone.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fTeleponKeyPressed

    private void fHandphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fHandphoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fContact.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fHandphoneKeyPressed

    private void fContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fContactKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fKota.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fContactKeyPressed

    private void fKotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKotaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fPropinsi.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fKotaKeyPressed

    private void fPropinsiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fPropinsiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fKeterangan.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fPropinsiKeyPressed

    private void fKeteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKeteranganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fHargaJual.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fKeteranganKeyPressed

    private void fKodeSalesmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKodeSalesmanActionPerformed
        SalesmanComboKlikKode();
    }//GEN-LAST:event_fKodeSalesmanActionPerformed

    private void fNamaSalesmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaSalesmanActionPerformed

    }//GEN-LAST:event_fNamaSalesmanActionPerformed

    private void fSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSimpanMouseClicked
        list = new ListRandom();
        kodecustomer = list.getKode_customer();
        System.out.println("fsimpan");
        System.out.println(dataTombol+kodecustomer);
        if(kodecustomer!="new"){
            System.out.println("/");
            edit();
            System.out.println("//");
        }else{
            if(" ".equals(fKode.getSelectedText()) || " ".equals(fLimit.getText()) || fHargaJual.getSelectedItem()==" " || fNamaSalesman.getSelectedItem()==" " || fHari.getSelectedItem()==" " || fTOP.getSelectedItem()==" "){
                JOptionPane.showMessageDialog(null, "Gagal, Lengkapi data sebelum di Save");
            }else{
                tambah();
            }
        }
    }//GEN-LAST:event_fSimpanMouseClicked

    private void fKodeSalesmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fKodeSalesmanMouseClicked
        if(evt.getClickCount() == 1){
            SalesmanComboKlikKode();
    }
    }//GEN-LAST:event_fKodeSalesmanMouseClicked

    private void fBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fBatalMouseClicked
        this.dispose();
        bersih();
        list = new ListRandom();
        list.setKode_customer("new");
    }//GEN-LAST:event_fBatalMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        bersih();
        list = new ListRandom();
        list.setKode_customer("new");
    }//GEN-LAST:event_formWindowClosed

    private void fHargaJualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fHargaJualKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fKodeSalesman.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fHargaJualKeyPressed

    private void fKodeSalesmanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKodeSalesmanKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fNamaSalesman.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fKodeSalesmanKeyPressed

    private void fNamaSalesmanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNamaSalesmanKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fHari.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fNamaSalesmanKeyPressed

    private void fHariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fHariKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fTOP.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fHariKeyPressed

    private void fTOPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTOPKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fLimit.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fTOPKeyPressed

    private void fLimitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fLimitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fSisa.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fLimitKeyPressed

    private void fSisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSisaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fWilayah.requestFocusInWindow();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fSisaKeyPressed

    private void fWilayahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fWilayahKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            fDeactive.requestFocusInWindow();
            fDeactive.setSelected(true);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fSimpan.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fWilayahKeyPressed

    private void fDeactiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fDeactiveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {     
           fActive.requestFocusInWindow();
           fActive.setSelected(true);
           fActive.isSelected();
       }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fSimpan.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
        if (evt.getKeyCode()==KeyEvent.VK_F2) {
            list = new ListRandom();
            kodecustomer = list.getKode_customer();
            System.out.println("fsimpan");
            System.out.println(dataTombol+kodecustomer);
            if(kodecustomer!="new"){
                System.out.println("/");
                edit();
                System.out.println("//");
            }else{
                if(" ".equals(fKode.getSelectedText()) || " ".equals(fLimit.getText()) || fHargaJual.getSelectedItem()==" " || fNamaSalesman.getSelectedItem()==" " || fHari.getSelectedItem()==" " || fTOP.getSelectedItem()==" "){
                    JOptionPane.showMessageDialog(null, "Gagal, Lengkapi data sebelum di Save");
                }else{
                    tambah();
                }
            }
        }
        
    }//GEN-LAST:event_fDeactiveKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_formKeyPressed

    private void fActiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fActiveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {     
           fDeactive.requestFocusInWindow();
           fDeactive.setSelected(true);
           fDeactive.isSelected();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fSimpan.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_F2) {
            list = new ListRandom();
            kodecustomer = list.getKode_customer();
            System.out.println("fsimpan");
            System.out.println(dataTombol+kodecustomer);
            if(kodecustomer!="new"){
                System.out.println("/");
                edit();
                System.out.println("//");
            }else{
                if(" ".equals(fKode.getSelectedText()) || " ".equals(fLimit.getText()) || fHargaJual.getSelectedItem()==" " || fNamaSalesman.getSelectedItem()==" " || fHari.getSelectedItem()==" " || fTOP.getSelectedItem()==" "){
                    JOptionPane.showMessageDialog(null, "Gagal, Lengkapi data sebelum di Save");
                }else{
                    tambah();
                }
            }
        }

    }//GEN-LAST:event_fActiveKeyPressed

    private void fSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSimpanKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            list = new ListRandom();
            kodecustomer = list.getKode_customer();
            System.out.println("fsimpan");
            System.out.println(dataTombol+kodecustomer);
            if(kodecustomer!="new"){
                System.out.println("/");
                edit();
                System.out.println("//");
            }else{
                if(" ".equals(fKode.getSelectedText()) || " ".equals(fLimit.getText()) || fHargaJual.getSelectedItem()==" " || fNamaSalesman.getSelectedItem()==" " || fHari.getSelectedItem()==" " || fTOP.getSelectedItem()==" "){
                    JOptionPane.showMessageDialog(null, "Gagal, Lengkapi data sebelum di Save");
                }else{
                    tambah();
                }
            }
        }
    }//GEN-LAST:event_fSimpanKeyPressed

    private void fDeactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fDeactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fDeactiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_Customer_NewEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_Customer_NewEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_Customer_NewEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_Customer_NewEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_Customer_NewEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton fActive;
    public javax.swing.JTextField fAlamat;
    private javax.swing.JLabel fBatal;
    public javax.swing.JTextField fContact;
    public javax.swing.JRadioButton fDeactive;
    public javax.swing.JTextField fHandphone;
    public javax.swing.JComboBox<String> fHargaJual;
    public javax.swing.JComboBox<String> fHari;
    public javax.swing.JTextField fKeterangan;
    public javax.swing.JTextField fKode;
    public javax.swing.JComboBox<String> fKodeSalesman;
    public javax.swing.JTextField fKota;
    public javax.swing.JTextField fLimit;
    public javax.swing.JTextField fNama;
    public javax.swing.JComboBox<String> fNamaSalesman;
    public javax.swing.JTextField fPropinsi;
    private javax.swing.JLabel fSimpan;
    public javax.swing.JTextField fSisa;
    public javax.swing.JComboBox<String> fTOP;
    public javax.swing.JTextField fTelepon;
    public javax.swing.JComboBox<String> fWilayah;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private void ComboKodeSalesman(){
        try{
            koneksi = new koneksi();
            String query ="SELECT kode_salesman, SUBSTRING(kode_salesman,1,2) * 1 AS URUT FROM salesman ORDER BY URUT ASC";
            hasil = koneksi.ambilData(query);
            System.out.println("///");
            while (hasil.next()){
                Object[] ob = new Object[1];
                ob[0] = hasil.getString(1);
                fKodeSalesman.addItem((String) ob[0]);
            }
            
            koneksi.tutupKoneksi(hasil);
        }catch(Exception e){
            System.out.println("salesman combo Nama");
        }
    }
    
    private void ComboNamaSalesman(){
        try{
            koneksi = new koneksi();
            String query ="SELECT nama_salesman, SUBSTRING(kode_salesman,1,2) * 1 AS URUT FROM salesman ORDER BY URUT ASC";
            hasil = koneksi.ambilData(query);
            System.out.println("///");
            while (hasil.next()){
                Object[] ob = new Object[1];
                ob[0] = hasil.getString(1);
                fNamaSalesman.addItem((String) ob[0]);
            }
            
            koneksi.tutupKoneksi(hasil);
        }catch(Exception e){
            System.out.println("salesman combo Nama");
        }
    }
    
    private void SalesmanComboKlikKode(){
        ComboKodeSalesman();
        kode_salesman = fKodeSalesman.getSelectedItem().toString();
        
        try{
            koneksi = new koneksi();
            String query ="Select nama_salesman from salesman where kode_salesman = '"+kode_salesman+"'";
            con = (Connection) koneksi.Connect();
            hasil = koneksi.ambilData(query);
            System.out.println("///");
            while (hasil.next()){
                fNamaSalesman.setSelectedItem(hasil.getString("nama_salesman"));
                System.out.println(hasil);
            }
        }catch(Exception e){
            System.out.println("salesman combo");
        }
    }
    
    private void SalesmanComboKlikNama(){
        nama_salesman = fNamaSalesman.getSelectedItem().toString();
        
        try{
            koneksi = new koneksi();
            String query ="Select kode_salesman from salesman where nama_salesman = '"+nama_salesman+"'";
            con = (Connection) koneksi.Connect();
            hasil = koneksi.ambilData(query);
            System.out.println("///");
            while (hasil.next()){
                fKodeSalesman.setSelectedItem(hasil.getString("kode_salesman"));
            }
        }catch(Exception e){
            System.out.println("salesman combo Nama");
        }
    }
    
//    private void TOPCombo(){
//        top = fTOP.getSelectedItem().toString();
//        try{
//            koneksi = new koneksi();
//            String query ="Select id_top from top where nama_top = '"+top+"'";
//            con = (Connection) koneksi.Connect();
//            hasil = koneksi.ambilData(query);
//            System.out.println("///");
//            while (hasil.next()){
//                id_top = hasil.getInt("id_top");
//            }
//        }catch(Exception e){
//            System.out.println("salesman combo Nama");
//        }
//    }
    
    private void WilayahCombo(){
        try{
            koneksi = new koneksi();
            String query ="Select nama_wilayah from wilayah";
            hasil = koneksi.ambilData(query);
            System.out.println("///");
            while (hasil.next()){
                Object[] ob = new Object[1];
                ob[0] = hasil.getString(1);
                fWilayah.addItem((String) ob[0]);
            }
            
            koneksi.tutupKoneksi(hasil);
        }catch(Exception e){
            System.out.println("salesman combo Nama");
        }
    }
    
    private String tampilNamaWilayah(int id_wilayah){
        try{
            koneksi = new koneksi();
            String query ="Select nama_wilayah from wilayah where kode_wilayah = '"+id_wilayah+"'";
            hasil = koneksi.ambilData(query);
            System.out.println("///");
            while (hasil.next()){
                System.out.println("11");
                nama_wilayah = hasil.getString("nama_wilayah");
                System.out.println("22");
            }
            System.out.println("33");
        }catch(Exception e){
            System.out.println("salesman combo Nama");
        }
        return nama_wilayah;
    }
    
    private void idHargaJual(){
        if(fHargaJual.getSelectedIndex()==0){
            hargaJual = 1;
        }
        if(fHargaJual.getSelectedIndex()==1){
            hargaJual = 2;
        }
        if(fHargaJual.getSelectedIndex()==2){
            hargaJual = 3;
        }
    }
    
    private void idWilayah(){
        wilayah = fWilayah.getSelectedItem().toString();
        try{
            String query = "Select kode_wilayah from wilayah where nama_wilayah = '"+wilayah+"'";
            hasil = koneksi.ambilData(query);
            while(hasil.next()){
               wilayah = hasil.getString("kode_wilayah");
               id_wilayah = Integer.parseInt(wilayah);
            }
        }catch(Exception e){
            System.out.println("id wilayah");
        }
    }
    
    private void radio(){
        if (fDeactive.isSelected()){
            fActive.setSelected(false);
            status = 0;
            System.out.println(status);
        }else{
            fActive.setSelected(false);
            status = 1;
            System.out.println(status);
        }
    }
    
    private void tambah(){
        if(!"".equals(fLimit.getText())){
        nama_salesman = fNama.getText();
        kota = fKode.getText();
        alamat = fAlamat.getText();
        propinsi = fPropinsi.getText();
        telepon = fTelepon.getText();
        contact = fContact.getText();
        handphone = fHandphone.getText();
        keterangan = fKeterangan.getText();
        
        idHargaJual();
        kode_salesman = fKodeSalesman.getSelectedItem().toString();
        hari = fHari.getSelectedItem().toString();
        LimitPiutang = Integer.parseInt(fLimit.getText());
        top = fTOP.getSelectedItem().toString();
        idWilayah();
        radio();
        
        int angka = 0;
        
        try{
            String query= "SELECT kode_customer, SUBSTRING(kode_customer,1,4) * 1 AS URUT FROM customer ORDER BY URUT DESC LIMIT 1";
            hasil = koneksi.ambilData(query);
            while(hasil.next()){
                angka = hasil.getInt("kode_customer");
                System.out.println(angka);
                
                id = angka+1;
                kodecustomer = String.valueOf(id);
                System.out.println("id"+kodecustomer);

                

                String sql= "Insert into customer values ('"+kodecustomer+"', "
                        + "'"+nama_salesman+"', '"+kota+"', '"+alamat+"', "
                        + "'"+propinsi+"', '"+telepon+"', '"+contact+"', "
                        + "'"+handphone+"', '"+keterangan+"', '"+hari+"', "
                        + "'"+status+"', '"+Integer.parseInt(kode_salesman)+"', '"+hargaJual+"', "
                        + "'"+top+"', '"+LimitPiutang+"', '"+id_wilayah+"')";
                System.out.println(sql);
                koneksi.simpanData(sql);

                JOptionPane.showMessageDialog(null,"Data sukses di input");
                this.dispose();

                
            }
            }catch (SQLException e){
            System.out.println();
        }
        }else{
            JOptionPane.showMessageDialog(null, "Gagal, Lengkapi data Limit Piutang");
        }
    }
    
    private void bersih(){
        id = 0;
        fKode.setText("");
        fNama.setText("");
        fAlamat.setText("");
        fTelepon.setText("");
        fHandphone.setText("");
        fKota.setText("");
        fPropinsi.setText("");
        fKeterangan.setText("");
        fLimit.setText("");
        fSisa.setText("");
        fHargaJual.setSelectedIndex(1);
        SalesmanComboKlikKode();
        SalesmanComboKlikNama();
        fKodeSalesman.setSelectedIndex(1);
        fNamaSalesman.setSelectedIndex(1);
    }
    
    private void tampilDataEdit(){
        list = new ListRandom();
        dataTombol = list.getTombol_salesman();
        kodecustomer = list.getKode_customer();
        System.out.println("fTampilDataEdit1");
        System.out.println(dataTombol+kodecustomer);
        
        try{
            String query= "SELECT kode_customer, nama_customer, alamat_customer, "
                    + "telepon_customer, handphone, contact_customer, "
                    + "kota_customer, provinsi_customer, keterangan, status_customer, "
                    + "limit_piutang, id_wilayah, id_top, kode_salesman, hari_tagihan, harga_jual, "
                    + "SUBSTRING(kode_customer,1,4) * 1 AS URUT FROM customer WHERE kode_customer = '"+kodecustomer+"'";
            con = (Connection) koneksi.Connect();
            hasil = koneksi.ambilData(query);
            while(hasil.next()){
                fKode.setText(kodecustomer);
                fNama.setText(hasil.getString(2));
                fAlamat.setText(hasil.getString(3));
                fTelepon.setText(hasil.getString(4));
                fHandphone.setText(hasil.getString(5));
                fContact.setText(hasil.getString(6));
                fKota.setText(hasil.getString(7));
                fPropinsi.setText(hasil.getString(8));
                fKeterangan.setText(hasil.getString(9));
                int id_status = hasil.getInt(10);
                if(id_status == 0){
                    fDeactive.setSelected(true);
                }else{
                    fActive.setSelected(true);
                }
                System.out.println("aa");
                fLimit.setText(String.valueOf(hasil.getInt(11)));
                System.out.println("aaaa");
                id_wilayah = hasil.getInt(12);
                System.out.println("aabbb");
                fTOP.setSelectedItem(hasil.getString(13));
                System.out.println("//");
                fKodeSalesman.setSelectedItem(hasil.getInt(14));
                System.out.println("///");
                fHari.setSelectedItem(hasil.getString(15));
                System.out.println("////");
                int hj = hasil.getInt(16);
                System.out.println("/////");
                if(hj == 1){
                    fHargaJual.setSelectedItem("Harga Jual 1");
                }else if(hj == 2){
                    fHargaJual.setSelectedItem("Harga Jual 2");
                }
                tampilNamaWilayah(id_wilayah);
                fWilayah.setSelectedItem(nama_wilayah);
                System.out.println("aabbbbb");
                fSisa.setText("0");
                }
            
            System.out.println("//////////");
            koneksi.tutupKoneksi(hasil);
        }catch(Exception e){
            System.out.println("error tampilDatEdit +"+e);
        }
    }
    
    private void edit(){
        try {
            koneksi = new koneksi();
            radio();
            idHargaJual();
            idWilayah();
            String kodes = fKodeSalesman.getSelectedItem().toString();
            list = new ListRandom();
            dataTombol = list.getTombol_salesman();
            kodecustomer = list.getKode_customer();
            
            String sql= "Update customer set nama_customer=?, "
                    + "kota_customer=?, alamat_customer=?, provinsi_customer=?, "
                    + "telepon_customer=?, contact_customer=?, handphone=?, "
                    + "keterangan=?, hari_tagihan=?, status_customer=?, "
                    + "kode_salesman=?, harga_jual=?, id_top=?, limit_piutang=?, "
                    + "id_wilayah=? where kode_customer=?" ;
            PreparedStatement p = (PreparedStatement) koneksi.Connect().prepareStatement(sql);
                p.setString(1, fNama.getText());
                p.setString(2, fKota.getText());
                p.setString(3, fAlamat.getText());
                p.setString(4, fPropinsi.getText());
                p.setString(5, fTelepon.getText());
                p.setString(6, fContact.getText());
                p.setString(7, fHandphone.getText());
                p.setString(8, fKeterangan.getText());
                p.setString(9, fHari.getSelectedItem().toString());
                p.setInt(10, status);
                p.setInt(11, Integer.parseInt(kodes));
                p.setInt(12, hargaJual);
                p.setString(13, fTOP.getSelectedItem().toString());
                p.setString(14, fLimit.getText());
                p.setInt(15, id_wilayah);
                p.setString(16, kodecustomer);
                p.executeUpdate();

                this.dispose();
                System.out.print(p);
                JOptionPane.showMessageDialog(null,"Data sukses di edit");
                bersih();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
